### ISSUE TITLE
can't use rpy2 inside reticulate-embedded python

### ISSUE THREAD

**Issue by xinstein** [rpy2/rpy2#942]
**Describe the issue or bug and how to reproduce**
run in R console
```
reticulate::import("rpy2.robjects")
```
will result in the following message being infinitely continuously printed
```
****found a symbol with attributes
****found a symbol with attributes
****found a symbol with attributes
```

My Package versions:
- windows 10 64bit
- R core : 4.1.3
- reticulate: 1.22
- rpy2: 3.4.5
- python: 3.7.12

**Expected behavior**
it shoud work

**Error**
```
****found a symbol with attributes
****found a symbol with attributes
****found a symbol with attributes
```

**Additional context**
I searched and tried a lot to resolve this issue, nothing works so far, sincerely need your help.

I am trying to use multiprocessing and rpy2 inside reticulate-embedded python. But the above problem indicates that I can't even get rpy2 alone to work in this setting.

**Comment by lgautier** [comment]
rpy2's current release series is 3.5.x. The 3.4.x releases are no longer maintained. Also, Windows is not well supported. I have reports that things work (worked?) well when used/installed with WLS (Windows Subsystem Linux).

Finally, try first if things are working without multiprocessing.

**Comment by xinstein** [comment]
> rpy2's current release series is 3.5.x. The 3.4.x releases are no longer maintained. Also, Windows is not well supported. I have reports that things work (worked?) well when used/installed with WLS (Windows Subsystem Linux).

Well, sadly I have virtualbox vms which are incompatible with wsl, also, GPU support is not as good as native windows. Is there any recent plan to improve support for windows?

I have upgraded to ```rpy2==3.5.4```, the exact same issue remains.

> 
> Finally, try first if things are working without multiprocessing.
The minimal bug-triggering example I provided doesn't contain multiprocessing.

**Comment by lgautier** [comment]
> > rpy2's current release series is 3.5.x. The 3.4.x releases are no longer maintained. Also, Windows is not well supported. I have reports that things work (worked?) well when used/installed with WLS (Windows Subsystem Linux).
> 
> Well, sadly I have virtualbox vms which are incompatible with wsl, also, GPU support is not as good as native windows. Is there any recent plan to improve support for windows?

I don't have plans but try to review (and.or ask opinions) & merge PRs.

> I have upgraded to `rpy2==3.5.4`, the exact same issue remains.
> 
> > Finally, try first if things are working without multiprocessing.
> 
> The minimal bug-triggering example I provided doesn't contain multiprocessing.

This eliminates a source of possibles issue around shared libraries and the way Windows handle them. This does not get me closer to providing help, unfortunately, as I do not know much about how this is working on Windows. Running this through a (C) debugger to find where the error message is originating from would be the next step. Hopefully someone here can provide more guidance than I can.

**Comment by lgautier** [comment]
Current `rpy2` and `reticulate` release are expected to work together without segfault. Importing `reticulate` from `rpy2` (`library("reticulate")` or other) will issue an informative about the minimum required version of `reticulate` (this may disappear in the future though). Reopen if still an issue.

**Comment by Obihoernchen80** [comment]
@xinstein Could you resolve your issue? Facing the same today.
I can import rpy2 inside python interpreter. When importing from R interpreter via reticulate I experience the issue you described.

windows 10 64bit
R core : 4.3.0
reticulate: 1.38.0
rpy2: 3.5.16
python: 3.10.11

**Comment by xinstein** [comment]
> @xinstein Could you resolve your issue? Facing the same today. I can import rpy2 inside python interpreter. When importing from R interpreter via reticulate I experience the issue you described.
> 
> windows 10 64bit R core : 4.3.0 reticulate: 1.38.0 rpy2: 3.5.16 python: 3.10.11

Sorry I can't be of any help on this issue, two years ago I circumvented this issue by eliminating all needs in my code to do such nested calling patterns. 

The justification for my choice is that such calling patterns, even if possible, are confusing and makes my project hard to maintain: does reticulate inside rpy2 make use of the caller python session? If not, do the different python instances interfere each other, like via shared environment variables?

But glad to notice this issue is already resolved.

**Comment by Obihoernchen80** [comment]
@lgautier
This exact issue is still present and prevents me from using databricks from R/windows when using 
sparlyr::spark_apply.

**Comment by Obihoernchen80** [comment]
@lgautier 
This exact issue is still present and prevents me from using databricks from R/windows when using
sparlyr::spark_apply.
Please reopen.

**Comment by lgautier** [comment]
I can certainly reopen the issue. rpy2 support for native Windows is limited though. If on Windows, consider using WSL and install Python, R, and rpy2 there.

**Comment by Obihoernchen80** [comment]
@lgautier  Thank you. Due to a restricted corporate environment I probably won't be able to use WSL but I'll give it a shot. I had hoped for a solution from rpy2/reticulate since a underlying issue has already been identified in https://github.com/rstudio/reticulate/issues/1638
